# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QuizProjectInSwiftUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QuizProjectInSwiftUI

  pod 'PKHUD'
  pod 'GRDB.swift'

  target 'QuizProjectInSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QuizProjectInSwiftUIUITests' do
    # Pods for testing
  end

end
